<?xml version="1.0" encoding="UTF-8"?>
<!-- Se quiere definir un lenguaje de marcas para representar los resultados de una liga de fútbol. 
    La información que se quiere almacenar de cada partido es:
        el nombre del equipo local
        el nombre del equipo visitante
        los goles marcados por el equipo local
        los goles marcados por el equipo visitante
    Escribe tres documentos que incluyan los siguientes resultados:
        Nottingham Presa: 0 - Inter de Mitente: 1
        Vodka Juniors: 3 - Sparta da Risa: 3
        Water de Múnich: 4 - Esteaua es del grifo: 2
    Cada documento incluirá un DTD diferente para representar ese lenguaje de marcas:
        una DTD en la que no haya atributos, sino únicamente etiquetas
        una DTD en la que los goles sean atributos
        una DTD en la que toda la información se guarde en forma de atributos-->
<!DOCTYPE resultados [
    <!ELEMENT resultados (resultado*)>
    <!ELEMENT resultado (equipoLocal, golesLocal, equipoVisitante, golesVisitante)>
    <!ELEMENT equipoLocal (#PCDATA)>
    <!ELEMENT equipoVisitante (#PCDATA)>
    <!ELEMENT golesLocal (#PCDATA)>
    <!ELEMENT golesVisitante (#PCDATA)>
]>
<resultados>
    <resultado>
        <equipoLocal>Nottingham Presa</equipoLocal>
        <golesLocal>0</golesLocal>
        <equipoVisitante>Inter de Mitente</equipoVisitante>
        <golesVisitante>1</golesVisitante>
    </resultado>
    <resultado>
        <equipoLocal>Vodka Juniors</equipoLocal>
        <golesLocal>3</golesLocal>
        <equipoVisitante>Sparta da Risa</equipoVisitante>
        <golesVisitante>3</golesVisitante>
    </resultado>
    <resultado>
        <equipoLocal>Water de Múnich</equipoLocal>
        <golesLocal>4</golesLocal>
        <equipoVisitante>Esteaua es del grifo</equipoVisitante>
        <golesVisitante>2</golesVisitante>
    </resultado>
</resultados>
